=== dnsfm/jigsaw-cms/agent/src/message/Parser/bin/lyvcmessage.dtd
<!--
     DTD for the LongCon Video Conference message definition file, Version 1.0
-->


<!-- ========== Top Level Elements ======================================== -->

<!-- 
    The "lyvcmessage" element is the root of the configuration file
    hierarchy, and contains nested elements for all of the other
    configuration settings.
-->

    <!ELEMENT lyvcmessage (name, desc, boolean*, date*, double*, float*, i4*, i8*, string*) >

<!-- 
    The "name" element gives the message name, this name should be unique, and be same
    with the message definition file name.
-->
        <!ELEMENT name (#PCDATA) >

<!-- 
    The "desc" element describe the function of the message, ie, in which situation, this
    message will be sent, and what action will be taken.
-->
        <!ELEMENT desc (#PCDATA) >

<!-- 
    The "boolean" element stands for a boolean attribute of the message.
-->
        <!ELEMENT boolean (#PCDATA) >

<!-- 
    The "date" element stands for a date attribute of the message.
-->
        <!ELEMENT date (#PCDATA) >

<!-- 
    The "double" element stands for a double attribute of the message.
-->
        <!ELEMENT double (#PCDATA) >

<!-- 
    The "float" element stands for a float attribute of the message.
-->
        <!ELEMENT float (#PCDATA) >

<!-- 
    The "i4" element stands for an integer attribute of the message, the size is 4 bytes.
-->
        <!ELEMENT i4 (#PCDATA) >

<!-- 
    The "i8" element stands for an integer attribute of the message, the size is 8 bytes.
-->
        <!ELEMENT i8 (#PCDATA) >

<!-- 
    The "string" element stands for an string attribute of the message.
-->
        <!ELEMENT string (#PCDATA) >

=== dnsfm/jigsaw-cms/agent/src/message/Parser/bin/AddContact.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE lyvcmessage SYSTEM "lyvcmessage.dtd">

<lyvcmessage>
    <name>AddContact</name>
    <desc>服务器发送给客户端，增加一个联系人</desc>
	<boolean>isCommon</boolean>
	<i4>status</i4>     
    <i8>groupId</i8>
	<i8>contactId</i8>
	<string>name</string>
	<string>email</string>
	<string>firstName</string>
	<string>lastName</string>
</lyvcmessage>

=== dnsfm/jigsaw-cms/agent/src/message/Parser/bin/ServerInfo.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE lyvcmessage SYSTEM "lyvcmessage.dtd">

<lyvcmessage>
    <name>ServerInfo</name>
    <desc>服务器发送给客户端，客户端用到的服务器网址</desc>
    <string>DeleteConferenceURL</string>
    <string>CreateConferenceNoticeURL</string>
    <string>CreateBulletinURL</string>
    <string>EditConferenceURL</string>
    <string>CommonContactMgrURL</string>
    <string>ConferenceModeMgrURL</string>
    <string>SystemRoleMgrURL</string>
    <string>CreateFormalConferenceURL</string>
    <string>SelfInfoMgrURL</string>
    <string>UserRegisterURL</string>
    <string>ClientDownloadURL</string>
</lyvcmessage>

=== dnsfm/jigsaw-cms/agent/src/message/Parser/bin/SendFileData.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE lyvcmessage SYSTEM "lyvcmessage.dtd">

<lyvcmessage>
    <name>SendFileData</name>
    <desc>文件传输的数据</desc>
    <boolean>isFirstSend</boolean>
    <boolean>isFinished</boolean>
    <i4>dataLength</i4>
    <i4>compressedLength</i4>
    <i8>receiverId</i8>
    <string>fullFileName</string>
    <string>fileData</string>
</lyvcmessage>
